### ISSUE TITLE
Button PIN incorrect

### ISSUE THREAD

**Issue by ferdinand0815** [bastelgarage/co2ampel#10]
Button not working (maybe only in my setup?)

++ #define BTNPIN 0       // D3 on Wemos D1 mini = 0

-- boolean btnPressed = !digitalRead(D3);
++  boolean btnPressed = !digitalRead(BTNPIN);

**Comment by fabaff** [comment]
See https://github.com/bastelgarage/co2ampel/issues/9#issuecomment-733614133

**Comment by ferdinand0815** [comment]
See #9
