### ISSUE TITLE
LED PIN wrong

### ISSUE THREAD

**Issue by ferdinand0815** [bastelgarage/co2ampel#9]
When compiled the LEDs do not work.

The LED PIN is defined as D8. However the GPIO PIN number needs to be used, which is 15.

--#define PIN D8
++#define PIN 15

**Comment by fabaff** [comment]
The [mapping](https://github.com/esp8266/Arduino/blob/master/variants/nodemcu/pins_arduino.h#L40-L50) takes care about the different naming schemas.

```c
static const uint8_t D8   = 15;
```

Thus both are valid representation of a pin.

**Comment by ferdinand0815** [comment]
I re-installed the ESP8266 repository and now it works... Sorry my mistake somehow.
